# Bài 1: Numpy Cơ Bản

In [1]:
import numpy as np

In [3]:
#tạo mảng 1 chiều từ 0 đến 9

print(np.arange(0, 10, 1))

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#tạo một mảng bool 3x3 với tất cả giá trị True

print(np.ones((3,3))>0)
print(np.ones((3,3), dtype=bool))
print(np.full((3,3), fill_value=True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [5]:
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [9]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [10]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5)&(a<=10))
print("result", a[index])

result [ 6  9 10]


In [11]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))


[6. 7. 9. 8. 9. 7. 5.]


In [13]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]


# Bài 2: Xử lý ảnh

In [17]:
%pip install gdown

     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     --------------------- ------------------ 30.7/57.6 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 57.6/57.6 kB 606.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
   ---------------------------------------- 78.3/78.3 kB 4.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import matplotlib.image as mpimg

In [20]:
#chuyển ảnh màu sang ảnh xám bằng phương pháp Lightness

img = mpimg.imread('./dog.jpeg')
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2
gray_img_01[0,0]

102.5

In [21]:
#chuyển ảnh màu sang ảnh xám bằng phương pháp Average

img = mpimg.imread('./dog.jpeg')
gray_img_02 = np.mean(img, axis=2)
gray_img_02[0,0]

107.66666666666667

In [22]:
#chuyển ảnh màu sang ảnh xám bằng phương pháp Luminosity

img = mpimg.imread('./dog.jpeg')
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03[0,0]

126.22999999999999

# Bài 3: Phân tích dữ liệu dạng bảng

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()

In [25]:
#lấy giá trị max và index tương ứng trên cột Sales
max_sales = df['Sales'].max()
max_index = df['Sales'].idxmax()
print(f"Max: {max_sales} - Index: {max_index}")

Max: 27.0 - Index: 175


In [26]:
#giá trị trung bình của cột TV
mean_tv = df['TV'].mean()
print(f"Giá trị trung bình của cột TV: {mean_tv}")


Giá trị trung bình của cột TV: 147.0425


In [27]:
#số lượng bảng ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20
count_sales_above_20 = df[df['Sales'] >= 20].shape[0]
print(f"Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20: {count_sales_above_20}")


Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20: 40


In [32]:
#giá trị trung bình của cột Radio thỏa mãn điều kiện giá trị tương ứng trên cột Sale lớn hơn hoặc bằng 15
mean_radio = df.loc[df['Sales'] >= 15, 'Radio'].mean()
print(f"Giá trị trung bình của cột Radio: {mean_radio}")

Giá trị trung bình của cột Radio: 26.22293577981651


In [33]:
#tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper
mean_newspaper = df['Newspaper'].mean()
total_sales = df.loc[df['Newspaper'] > mean_newspaper, 'Sales'].sum()
print(f"Tổng các hàng của cột Sales: {total_sales}")

Tổng các hàng của cột Sales: 1405.1


In [34]:
#tạo mảng scores dựa trên giá trị trung bình của cột Sales

# Tính giá trị trung bình của cột Sales
A = df['Sales'].mean()

# Tạo mảng scores
scores = []
for value in df['Sales']:
    if value > A:
        scores.append('Good')
    elif value < A:
        scores.append('Bad')
    else:
        scores.append('Average')

# In ra kết quả scores[7:10]
print(scores[7:10])

['Bad', 'Bad', 'Good']


In [35]:
#tính giá trị gần nhất với giá trị trung bình

closest_value = df['Sales'].iloc[(df['Sales'] - A).abs().argsort()[:1]]

# Tạo mảng scores tương tự
scores_closest = []
for value in df['Sales']:
    if value > A:
        scores_closest.append('Good')
    elif value < A:
        scores_closest.append('Bad')
    else:
        scores_closest.append('Average')

# In ra kết quả scores[7:10]
print(scores_closest[7:10])

['Bad', 'Bad', 'Good']
